name: Deploy to Pantheon
on:
  push:
    branches:
      - 'master'
env:
  SSH_PRIVATE_KEY: ${{ secrets.PANTHEON_SSH_KEY }}

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: deploy to Pantheon
      run: |
        echo "$SSH_PRIVATE_KEY" > ../private.key
        chmod 600 ../private.key
        eval `ssh-agent -s`
        ssh-add ../private.key

    - name: deployer
      env:
        pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
      run: |
        git remote add pantheon $pantheon_repo
        git push pantheon HEAD:master
