name: Deploy to Pantheon
on:
  push:
    branches:
      - '*'
      - '!master'
env:
  pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
  pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PANTHEON_SSH_KEY }}
        config: ${{ secrets.SSH_CONFIG }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Setup PHP
      uses: shivammathur/setup-php@c0c6e403b6c6c44657450627093edddf3b905c5b # 2.9.0
      with:
        php-version: '7.4'

    - name: Install Terminus
      run: |
        composer global require consolidation/cgr:^2.0.5
        cgr pantheon-systems/terminus:^2.6.1
        terminus auth:login --machine-token=${{ secrets.PANTHEON_MACHINE_TOKEN }}

    - name: deployer
      run: |
        BASE_BRANCH=${GITHUB_REF##*/}
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git remote add pantheon $pantheon_repo
        git push --force pantheon HEAD:$BASE_BRANCH
        terminus multidev:create $pantheon_site_name.dev $BASE_BRANCH
